module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        ":books: docs",
        ":bug: fix",
        ":sparkles: feat",
        ":bricks: ci",
        ":recycle: refactor",
        ":zap: perf",
        ":boom: fix",
        ":lipstick: feat",
        ":test_tube: test",
        ":bulb: docs",
        ":card_file_box: raw",
        ":wrench: chore",
      ],
    ],
    "type-case": [0],
    "type-empty": [0],
    "scope-empty": [0],
    "scope-case": [0],
    "subject-case": [0],
    "subject-empty": [0],
    "subject-full-stop": [0],
    "header-max-length": [0],
  },
};
